export const ROUTES = {
  HOME: 'Home' as const,
  CARD: 'Card' as const,
  SIMS: 'Sims' as const,
  YODA: 'Yoda' as const,
  STICKY_HEADER_FLATLIST: 'StickyHeaderFlatList' as const,
  STICKY_HEADER_SCROLLVIEW: 'StickyHeaderScrollView' as const,
  STICKY_HEADER_SECTIONLIST: 'StickyHeaderSectionList' as const,
  TABBED_HEADER_LIST: 'TabbedHeaderList' as const,
  TABBED_HEADER_PAGER: 'TabbedHeaderPager' as const,
  AVATAR_HEADER_FLATLIST: 'AvatarHeaderFlatList' as const,
  AVATAR_HEADER_SCROLLVIEW: 'AvatarHeaderScrollView' as const,
  AVATAR_HEADER_SECTIONLIST: 'AvatarHeaderSectionList' as const,
  DETAILS_HEADER_FLATLIST: 'DetailsHeaderFlatList' as const,
  DETAILS_HEADER_SCROLLVIEW: 'DetailsHeaderScrollView' as const,
  DETAILS_HEADER_SECTIONLIST: 'DetailsHeaderSectionList' as const,
};
