export const homeScreenTestIDs = Object.freeze({
  headerTitle: 'HeaderTitleTestID',
  popularQuizesTab: 'PopularQuizesTabTestID',
  popularQuizesHeader: 'PopularQuizesHeaderTestID',
  productDesignTab: 'ProductDesignTabTestID',
  productDesignHeader: 'ProductDesignHeaderTestID',
  developmentTab: 'DevelopmentTabTestID',
  developmentHeader: 'DevelopmentHeaderTestID',
  projectManagementTab: 'ProjectManagementTabTestID',
  projectManagementHeader: 'ProjectManagementHeaderTestID',
  yodaLink: 'YodaLinkTestID',
  simsLink: 'SimsLinkTestID',
  stickyHeaderFlatListLink: 'StickyHeaderFlatListLinkTestID',
  stickyHeaderScrollViewLink: 'StickyHeaderScrollViewLinkTestID',
  stickyHeaderSectionListLink: 'StickyHeaderSectionListLinkTestID',
  tabbedHeaderListLink: 'TabbedHeaderListLinkTestID',
  tabbedHeaderPagerLink: 'TabbedHeaderPagerLinkTestID',
  avatarHeaderFlatListLink: 'AvatarHeaderFlatListLinkTestID',
  avatarHeaderScrollViewLink: 'AvatarHeaderScrollViewLinkTestID',
  avatarHeaderSectionListLink: 'AvatarHeaderSectionListLinkTestID',
  detailsHeaderFlatListLink: 'DetailsHeaderFlatListLinkTestID',
  detailsHeaderScrollViewLink: 'DetailsHeaderScrollViewLinkTestID',
  detailsHeaderSectionListLink: 'DetailsHeaderSectionListLinkTestID',
  tabbedHeaderWithSectionLists: 'TabbedHeaderWithSectionListsTestID',
});
